version: '3.7'

volumes:
    logs:
        driver: local
    mysql-volume:
        driver: local

services:
    slim:
        image: php:8-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: 'true'
        ports:
            - '8080:8081'
        volumes:
            - .:/var/www
            - logs:/var/www/logs

    mysql:
        image: mysql:8.0
        container_name: slim-mysql
        environment:
            MYSQL_ROOT_PASSWORD: yourpassword
            MYSQL_DATABASE: yourdatabase
        ports:
            - '3306:3306'
        volumes:
            - mysql-volume:/var/lib/mysql
